Begin
        
        INSERT INTO SOFTWARE (PID, PNAME, SPLACE, COURSE, CCOST) VALUES ('P002', 'SkyLinePro', 'PRAGATHI', 'MCA', 15000.00);
        INSERT INTO SOFTWARE (PID, PNAME, SPLACE, COURSE, CCOST) VALUES ('P003', 'InstaFlow', 'JMI', 'MSc AI/ML', 20000.00);
        INSERT INTO SOFTWARE (PID, PNAME, SPLACE, COURSE, CCOST) VALUES ('P004', 'ZenGrid', 'NIT', 'BSc Bio', 25000.00);
        INSERT INTO SOFTWARE (PID, PNAME, SPLACE, COURSE, CCOST) VALUES ('P005', 'OptiManage', 'Pentafour', 'BTech CS', 30000.00);
        INSERT INTO SOFTWARE (PID, PNAME, SPLACE, COURSE, CCOST) VALUES ('P006', 'PixelCraft', 'PRAGATHI', 'PGDCA', 10000.00); 
        INSERT INTO SOFTWARE (PID, PNAME, SPLACE, COURSE, CCOST) VALUES ('P007', 'CodePulse', 'JMI', 'MCA', 15000.00);
        INSERT INTO SOFTWARE (PID, PNAME, SPLACE, COURSE, CCOST) VALUES ('P008', 'DataSpring', 'NIT', 'MSc AI/ML', 20000.00);
        INSERT INTO SOFTWARE (PID, PNAME, SPLACE, COURSE, CCOST) VALUES ('P009', 'BrightMind', 'Pentafour', 'BSc Bio', 25000.00);
        INSERT INTO SOFTWARE (PID, PNAME, SPLACE, COURSE, CCOST) VALUES ('P010', 'AeroLink', 'PRAGATHI', 'BTech CS', 30000.00);
end;
/